export const messages = {
  'zh-CN': {
    nav: { home: '首页', about: '认识 DB', projects: '作品柜', tools: '小工具', blog: '碎碎念' },
    common: { viewAll: '全部端上来', open: '拆开看看', back: '原路返回', repo: '去 GitHub 看源码', demo: '打开成品', read: '接着往下看', min: '分钟读完', menu: '打开菜单', brandHome: '返回 DB 首页', primaryNav: '主导航', mobileNav: '移动端导航', lightTheme: '开灯看看', darkTheme: '关灯看看', search: '搜点什么', clear: '清空筛选', copied: '复制好了', copyFailed: '复制失败', copy: '复制代码', copyLink: '复制文章链接', linkCopied: '链接已复制' },
    home: { eyebrow: 'DB SAMA / 思考停止区', titleA: 'oi，想和 DB SAMA', titleB: '一起停止思考吗？', intro: '来自 DB 的信号', projects: '替身般的小工具', posts: '没想明白的随笔', enterEssays: '进入随笔', playgroundTitle: '别让灵感原地罚站。', playgroundDescription: '这里有节点、关系和一点点不安分。移动指针，看它们临时开个会。', playgroundInteraction: '指针 / 搅局器' },
    tools: { eyebrow: 'TOOLS / 实用工具', title: '随手可用的工具', subtitle: '无需上传数据，在浏览器中完成常见开发任务。', search: '搜索工具或标签', empty: '未找到工具', input: '输入待处理内容', output: '处理结果', run: '运行工具', invalidJson: 'JSON 格式无效，请检查后重试。', favorite: '收藏工具', unfavorite: '取消收藏', recentTitle: '最近访问', clearRecent: '清除记录', resultsLabel: '工具目录', results: '项工具', categories: { all: '全部类型', creative: '创意工具', utility: '实用工具' }, filters: { all: '全部工具', favorites: '已收藏', recent: '最近使用' }, statuses: { 'coming-soon': '即将上线', online: '已上线', paused: '已暂停' } },
    about: { eyebrow: 'ABOUT / DB 使用说明', title: '你以为这里有一份正经简介？', bio: '残念！这里只有 DB，一个会把脑内噪音做成小工具、再把剩下的噪音写成随笔的人。', identity: '本体信息', github: 'DB 的 GitHub', capabilities: '随身工具箱', principles: '停止思考守则', facts: ['先停止思考，再偷偷做完', '不会的先假装是实验', '踩过的坑写下来再走', '小东西也要认真胡闹'] },
    projects: { eyebrow: 'PROJECTS / 怪东西陈列柜', title: '做过的，和还没做完的。', subtitle: 'DB 做过但还没舍得删的东西。放心，它们大多不会突然发动时间停止。', empty: '这里空得像 DB 的大脑。', overview: '这是什么', stack: '拿什么做的', filter: '按进度筛选', all: '全都看看', online: '能用了', building: '还在搓', archived: '先放着', search: '搜项目或技术栈' },
    blog: { eyebrow: 'ESSAYS / 思考残骸', title: '随笔与笔记', subtitle: '想明白之前先写下来。写完还没想明白的话，就把它叫作随笔。', all: '全部随笔', filter: '按类型筛选', search: '搜标题、摘要或标签', results: '篇随笔', empty: '没有随笔。DB 可能真的停止思考了。', kinds: { daily: '日常', inspiration: '灵光一闪', technical: '技术折腾' } },
    notFound: { code: 'BIZARRE_ROUTE_NOT_FOUND', title: '你抵达了连 DB SAMA 都没想过的世界线。', action: '返回首页' },
    footer: '别急，DB 也没想明白。', status: '思考暂停，网站正常', language: 'EN',
  },
  en: {
    nav: { home: 'Home', about: 'Meet DB', projects: 'Projects', tools: 'Tiny Tools', blog: 'Field Notes' },
    common: { viewAll: 'Bring out the rest', open: 'Take a look', back: 'Back we go', repo: 'See source on GitHub', demo: 'Open the real thing', read: 'Keep reading', min: 'min to read', menu: 'Open menu', brandHome: 'Back to DB home', primaryNav: 'Primary navigation', mobileNav: 'Mobile navigation', lightTheme: 'Turn the lights on', darkTheme: 'Turn the lights off', search: 'Find something', clear: 'Clear filters', copied: 'Copied and ready', copyFailed: 'Copy failed', copy: 'Copy code', copyLink: 'Copy article link', linkCopied: 'Link copied' },
    home: { eyebrow: 'DB-SAMA / THINKING-FREE ZONE', titleA: 'Oi, want to stop thinking', titleB: 'with DB-sama?', intro: 'A signal from DB', projects: 'Stand-like little tools', posts: 'Essays written too early', enterEssays: 'Enter essays', playgroundTitle: 'Do not leave ideas standing still.', playgroundDescription: 'Nodes, relationships, and a little harmless chaos. Move the pointer and watch them call an emergency meeting.', playgroundInteraction: 'Pointer / troublemaker' },
    tools: { eyebrow: 'TOOLS / UTILITIES', title: 'Tools ready to use', subtitle: 'Handle everyday development tasks in the browser without uploading your data.', search: 'Search tools or tags', empty: 'No tools found', input: 'Enter content to process', output: 'Result', run: 'Run tool', invalidJson: 'Invalid JSON. Check the input and try again.', favorite: 'Favorite tool', unfavorite: 'Remove favorite', recentTitle: 'Recently visited', clearRecent: 'Clear history', resultsLabel: 'Tool directory', results: 'tools', categories: { all: 'All kinds', creative: 'Creative', utility: 'Utility' }, filters: { all: 'All tools', favorites: 'Favorites', recent: 'Recent' }, statuses: { 'coming-soon': 'Coming soon', online: 'Online', paused: 'Paused' } },
    about: { eyebrow: 'ABOUT / DB USER GUIDE', title: 'You expected a serious bio?', bio: 'Too bad. It is just DB, turning brain noise into tiny tools and the remaining noise into essays.', identity: 'Who is this', github: 'DB on GitHub', capabilities: 'Tools of the trade', principles: 'Rules for not thinking', facts: ['Stop thinking, then secretly finish it', 'Call the unknown parts experiments', 'Write down the wrong turns', 'Take tiny nonsense seriously'] },
    projects: { eyebrow: 'PROJECTS / CABINET OF ODDITIES', title: 'Made, making, and maybe abandoned.', subtitle: 'Things DB made and still refuses to delete. Most of them probably cannot stop time.', empty: 'As empty as DB’s mind right now.', overview: 'What is this', stack: 'Made with', filter: 'Filter by progress', all: 'Show everything', online: 'It works', building: 'Still cooking', archived: 'On the shelf', search: 'Search projects or stack' },
    blog: { eyebrow: 'ESSAYS / THOUGHT DEBRIS', title: 'Essays and notes', subtitle: 'Write it down before it makes sense. If it still does not make sense afterward, call it an essay.', all: 'All essays', filter: 'Filter by kind', search: 'Search titles, excerpts, or tags', results: 'essays', empty: 'No essays. DB-sama may have actually stopped thinking.', kinds: { daily: 'Daily', inspiration: 'Brainwave', technical: 'Technical tinkering' } },
    notFound: { code: 'BIZARRE_ROUTE_NOT_FOUND', title: 'You reached a bizarre timeline even DB-sama never imagined.', action: 'Return home' },
    footer: 'Relax. DB has not figured it out either.', status: 'Thinking paused, site operational', language: '中',
  },
} as const
